In [17]:
import pandas as pd
from pathlib import Path
import os
from dotenv import dotenv_values

In [23]:
data_path = Path(os.path.abspath('')).resolve().parent / "data.csv"
env_path = Path(os.path.abspath('')).resolve().parent / "secrets.env"

df = pd.read_csv(data_path)

env_vars = dotenv_values(env_path)
# Filter out bad coordinates

df = df.dropna(subset = ['longitude', 'latitude'])
df = df[(df['longitude'] != 0) & (df['latitude'] != 0)]

df['street_name'] = df['street_name'].apply(lambda x : x.title())

df['address'] = df.apply(lambda x : str(x['house_number']) + ' ' + x['street_name'] ,axis = 1)
print(df.shape)
df.head()

(970, 26)

,inspection_type,job_ticket_or_work_order_id,job_id,job_progress,bbl,boro_code,block,lot,house_number,street_name,...,location,community_board,council_district,census_tract,bin,nta,approved_date,x_coord,y_coord,address
0,BAIT,3056322,PC8487803,5,3.019150e+09,3,1915,61,284,Clinton Avenue,...,"{'latitude': '40.689887042515', 'longitude': '...",2.0,35.0,195.0,3055028.0,Clinton Hill,NaN,NaN,NaN,284 Clinton Avenue
1,Initial,14208272,PC8635827,1,3.030980e+09,3,3098,19,172,Seigel Street,...,"{'latitude': '40.704790525696', 'longitude': '...",1.0,34.0,489.0,3071470.0,East Williamsburg,2025-12-09T14:52:51.000,NaN,NaN,172 Seigel Street
2,BAIT,3056363,PC8548734,7,3.051220e+09,3,5122,10,116,East 19 Street,...,"{'latitude': '40.646503808371', 'longitude': '...",14.0,40.0,512.0,3117591.0,Flatbush,NaN,994915.0,174820.0,116 East 19 Street
3,BAIT,3056271,PC8612711,6,1.021080e+09,1,2108,52,469,West 157 Street,...,"{'latitude': '40.832524213959', 'longitude': '...",12.0,10.0,239.0,1062508.0,Washington Heights (South),2025-12-11T11:30:29.000,1000516.0,242596.0,469 West 157 Street
4,BAIT,3056414,PC8609532,4,2.033570e+09,2,3357,248,415,East 204 Street,...,"{'latitude': '40.870789389041', 'longitude': '...",7.0,11.0,425.0,2018686.0,Norwood,2025-12-09T09:20:49.000,NaN,NaN,415 East 204 Street

In [24]:
test_row = df.iloc[0]

for row in df.head(10).iterrows():
    latitude = row[1]['latitude']
    longitude = row[1]['longitude']
    address = row[1]['address']
    print(latitude, longitude, address)

40.689887042515 -73.968177844567 284 Clinton Avenue
40.704790525696 -73.939378259695 172 Seigel Street
40.646503808371 -73.961568071532 116 East   19 Street
40.832524213959 -73.94122003788 469 West  157 Street
40.870789389041 -73.87651098883 415 East 204 Street
40.767160410349 -73.897685854609 71-11 Astoria Boulevard N
40.790615419424 -73.948436619708 122 East 103 Street
40.71526031998 -73.984420123573 460 Grand Street
40.682307685049 -73.964644481108 554 Washington Avenue
40.682307685049 -73.964644481108 554 Washington Avenue

In [6]:
print(results)

NameError: name 'results' is not defined

In [ ]:
import requests
import json

# Los tacos lat/lon

lat = 40.7065340451609
lon = -74.0116639196217

# Demo
                # "latitude": 37.7937,
                # "longitude": -122.3965

# Replace with your actual API Key
API_KEY = env_vars['GOOGLE_PLACES_API_KEY']

# The endpoint for the Nearby Search (New) API
url = "https://places.googleapis.com/v1/places:searchNearby"

# Define the request body as a Python dictionary
# This example searches for restaurants within a 500-meter radius
# around a specific latitude and longitude.
request_body = {
    "includedTypes": ["restaurant", "meal_delivery", "meal_takeaway", "bakery", "bar", "cafe"],
    "maxResultCount": 20,
    "locationRestriction": {
        "circle": {
            "center": {
                "latitude": lat,
                "longitude": lon
            },
            "radius": 500.0
        }
    }
}

# Define the headers for the request
# X-Goog-Api-Key is used for authentication.
# X-Goog-FieldMask specifies which fields to return in the response.
# It's good practice to only request the fields you need to save on processing time and billing.
headers = {
    "Content-Type": "application/json",
    "X-Goog-Api-Key": API_KEY,
    "X-Goog-FieldMask": "places.displayName,places.formattedAddress,places.location,places.rating"
}

try:
    # Make the POST request
    # The 'json' parameter in requests.post automatically serializes the dictionary to JSON
    # and sets the 'Content-Type' header to 'application/json'.
    response = requests.post(url, headers=headers, json=request_body)

    # Check if the request was successful (status code 200)
    if response.status_code == 200:
        response_data = response.json()
        print("Nearby Search Results:")
        if response_data and "places" in response_data:
            for place in response_data["places"]:
                display_name = place.get("displayName", {}).get("text", "N/A")
                formatted_address = place.get("formattedAddress", "N/A")
                location = place.get("location", {})
                rating = place.get("rating", "N/A")
                print(f"  Name: {display_name}")
                print(f"  Address: {formatted_address}")
                print(f"  Location: Latitude {location.get('latitude')}, Longitude {location.get('longitude')}")
                print(f"  Rating: {rating}")
                print("-" * 20)
        else:
            print("No places found or unexpected response format.")
    else:
        print(f"Error: Request failed with status code {response.status_code}")
        print(f"Response: {response.text}")

except requests.exceptions.RequestException as e:
    print(f"An error occurred: {e}")

In [ ]:
# pd.DataFrame(response_data['places'])
request_body['locationRestriction']['circle']['center']['latitude']
request_body['locationRestriction']['circle']['center']['longitude']

40.7065340451609

In [32]:
# Replace with your actual API Key
API_KEY = env_vars['GOOGLE_PLACES_API_KEY']

# The endpoint for the Nearby Search (New) API
url = "https://places.googleapis.com/v1/places:searchNearby"

# Define the request body as a Python dictionary
# This example searches for restaurants within a 500-meter radius
# around a specific latitude and longitude.
request_body = {
    "includedTypes": ["restaurant", "meal_delivery", "meal_takeaway", "bakery", "bar", "cafe"],
    "maxResultCount": 20,
    "locationRestriction": {
        "circle": {
            "center": {
                "latitude": 0,
                "longitude": 0
            },
            "radius": 500.0
        }
    }
}

requested_places = pd.DataFrame()


for row in df.head(3).iterrows():

    temp_df = pd.DataFrame()

    latitude = row[1]['latitude']
    longitude = row[1]['longitude']
    address = row[1]['address']
    
    try:
        # Make the POST request
        # The 'json' parameter in requests.post automatically serializes the dictionary to JSON
        # and sets the 'Content-Type' header to 'application/json'.

        # Reset for every iteration
        request_body['locationRestriction']['circle']['center']['latitude'] = latitude
        request_body['locationRestriction']['circle']['center']['longitude'] = longitude

        # Make request
        response = requests.post(url, headers=headers, json=request_body)

        # Check if the request was successful (status code 200)
        if response.status_code == 200:
            response_data = response.json()
            print("Nearby Search Results:")
            if response_data and "places" in response_data:
                for place in response_data["places"]:
                    display_name = place.get("displayName", {}).get("text", "N/A")
                    formatted_address = place.get("formattedAddress", "N/A")
                    location = place.get("location", {})
                    rating = place.get("rating", "N/A")
                    print(f"  Name: {display_name}")
                    print(f"  Address: {formatted_address}")
                    print(f"  Location: Latitude {location.get('latitude')}, Longitude {location.get('longitude')}")
                    print(f"  Rating: {rating}")
                    print("-" * 20)
            else:
                print("No places found or unexpected response format.")
        else:
            print(f"Error: Request failed with status code {response.status_code}")
            print(f"Response: {response.text}")

    except requests.exceptions.RequestException as e:
        print(f"An error occurred: {e}")
    
    if response_data:
        temp_df = pd.DataFrame(response_data['places'])
        temp_df['latitude'] = latitude
        temp_df['longitude'] = longitude
        temp_df['address'] = address
        
        requested_places = pd.concat([requested_places, temp_df])
    else:
        print("Nothing returned!")
        print(response_data)

Nearby Search Results:
  Name: Miss Ada
  Address: 184 DeKalb Ave, Brooklyn, NY 11205, USA
  Location: Latitude 40.689425, Longitude -73.9723664
  Rating: 4.6
--------------------
  Name: Olea
  Address: 171 Lafayette Ave, Brooklyn, NY 11238, USA
  Location: Latitude 40.6878197, Longitude -73.9706231
  Rating: 4.6
--------------------
  Name: LaRina Pastificio & Vino
  Address: 387 Myrtle Ave, Brooklyn, NY 11205, USA
  Location: Latitude 40.6933422, Longitude -73.97042200000001
  Rating: 4.7
--------------------
  Name: Walter's
  Address: 166 DeKalb Ave, Brooklyn, NY 11217, USA
  Location: Latitude 40.6895015, Longitude -73.9732615
  Rating: 4.4
--------------------
  Name: Sailor
  Address: 228 DeKalb Ave, Brooklyn, NY 11205, USA
  Location: Latitude 40.6893831, Longitude -73.9703111
  Rating: 4.4
--------------------
  Name: Rhodora Wine Bar
  Address: 197 Adelphi St, Brooklyn, NY 11205, USA
  Location: Latitude 40.6917328, Longitude -73.9714244
  Rating: 4.3
--------------------
  Name: Evelina
  Address: 211 DeKalb Ave, Brooklyn, NY 11205, USA
  Location: Latitude 40.6897385, Longitude -73.970998
  Rating: 4.7
--------------------
  Name: Colonia Verde
  Address: 219 DeKalb Ave, Brooklyn, NY 11205, USA
  Location: Latitude 40.689699399999995, Longitude -73.9707225
  Rating: 4.6
--------------------
  Name: Brooklyn Public House
  Address: 247 DeKalb Ave, Brooklyn, NY 11205, USA
  Location: Latitude 40.689590599999995, Longitude -73.96936459999999
  Rating: 4.5
--------------------
  Name: Mango Bay
  Address: 271 Adelphi St, Brooklyn, NY 11205, USA
  Location: Latitude 40.6894104, Longitude -73.9708886
  Rating: 4.4
--------------------
  Name: Black Iris
  Address: 120 Lafayette Ave, Brooklyn, NY 11238, USA
  Location: Latitude 40.687308699999996, Longitude -73.9724778
  Rating: 4.7
--------------------
  Name: Chef Katsu Brooklyn
  Address: 143 Greene Ave, Brooklyn, NY 11238, USA
  Location: Latitude 40.6868, Longitude -73.9663178
  Rating: 4.6
--------------------
  Name: Roman's
  Address: 243 DeKalb Ave, Brooklyn, NY 11205, USA
  Location: Latitude 40.689633, Longitude -73.96953979999999
  Rating: 4.6
--------------------
  Name: Farmer in the Deli
  Address: 357 Myrtle Ave, Brooklyn, NY 11205, USA
  Location: Latitude 40.693401099999996, Longitude -73.97174009999999
  Rating: 4.6
--------------------
  Name: Prima Brooklyn
  Address: 147 Greene Ave, Brooklyn, NY 11238, USA
  Location: Latitude 40.6868526, Longitude -73.96623819999999
  Rating: 4.4
--------------------
  Name: Myrtle Thai
  Address: 438 Myrtle Ave, Brooklyn, NY 11205, USA
  Location: Latitude 40.692969, Longitude -73.96807869999999
  Rating: 4.8
--------------------
  Name: Aita
  Address: 132 Greene Ave, Brooklyn, NY 11238, USA
  Location: Latitude 40.6864911, Longitude -73.9666422
  Rating: 4.6
--------------------
  Name: Brooklyn Music Kitchen
  Address: 177 Vanderbilt Ave, Brooklyn, NY 11205, USA
  Location: Latitude 40.692643, Longitude -73.9694925
  Rating: 4.2
--------------------
  Name: Dick and Jane’s
  Address: 266 Adelphi St, Brooklyn, NY 11205, USA
  Location: Latitude 40.689854, Longitude -73.971357
  Rating: 4.4
--------------------
  Name: Dinner Party
  Address: 274 Hall St, Brooklyn, NY 11205, USA
  Location: Latitude 40.6900427, Longitude -73.9654379
  Rating: 4.4
--------------------
Nearby Search Results:
  Name: Win Son Bakery
  Address: 164 Graham Ave, Brooklyn, NY 11206, USA
  Location: Latitude 40.707242699999995, Longitude -73.94296589999999
  Rating: 4.5
--------------------
  Name: 3 Dollar Bill
  Address: 260 Meserole St, Brooklyn, NY 11206, USA
  Location: Latitude 40.7084419, Longitude -73.93820319999999
  Rating: 4.3
--------------------
  Name: Roberta's
  Address: 261 Moore St, Brooklyn, NY 11206, USA
  Location: Latitude 40.705081, Longitude -73.9335834
  Rating: 4.5
--------------------
  Name: Win Son
  Address: 159 Graham Ave, Brooklyn, NY 11206, USA
  Location: Latitude 40.7074661, Longitude -73.9434952
  Rating: 4.5
--------------------
  Name: Sleepwalk
  Address: 251 Bushwick Ave, Brooklyn, NY 11206, USA
  Location: Latitude 40.7073293, Longitude -73.93954459999999
  Rating: 4.7
--------------------
  Name: CLEO'S
  Address: 222 Varet St, Brooklyn, NY 11206, USA
  Location: Latitude 40.7037875, Longitude -73.9344706
  Rating: 4.9
--------------------
  Name: Dun-Well Doughnuts
  Address: 222 Montrose Ave, Brooklyn, NY 11206, USA
  Location: Latitude 40.7074134, Longitude -73.9402643
  Rating: 4.6
--------------------
  Name: duckduck
  Address: 153 Montrose Ave, Brooklyn, NY 11206, USA
  Location: Latitude 40.7074778, Longitude -73.9429899
  Rating: 4.4
--------------------
  Name: Lulla's Bakery - Grand Café & Cocktails
  Address: 169 Graham Ave, Brooklyn, NY 11206, USA
  Location: Latitude 40.7078148, Longitude -73.9435045
  Rating: 4.3
--------------------
  Name: Taqueria El Torito
  Address: 32 Varet St, Brooklyn, NY 11206, USA
  Location: Latitude 40.702832099999995, Longitude -73.9435373
  Rating: 4.7
--------------------
  Name: Sweet Science
  Address: 135 Graham Ave, Brooklyn, NY 11206, USA
  Location: Latitude 40.7064375, Longitude -73.943238
  Rating: 4.2
--------------------
  Name: IHOP
  Address: 785 Flushing Ave, Brooklyn, NY 11206, USA
  Location: Latitude 40.7010024, Longitude -73.94124049999999
  Rating: 3.8
--------------------
  Name: Tradesman
  Address: 222 Bushwick Ave, Brooklyn, NY 11206, USA
  Location: Latitude 40.708203999999995, Longitude -73.940074
  Rating: 4.6
--------------------
  Name: MAMATACO
  Address: 880 Flushing Ave, Brooklyn, NY 11206, USA
  Location: Latitude 40.7018895, Longitude -73.936578
  Rating: 3.9
--------------------
  Name: The Brooklyn Tree
  Address: 188 Montrose Ave, Brooklyn, NY 11206, USA
  Location: Latitude 40.7073209, Longitude -73.94184659999999
  Rating: 4.5
--------------------
  Name: Caridad China
  Address: 108 Graham Ave, Brooklyn, NY 11206, USA
  Location: Latitude 40.7049447, Longitude -73.9426017
  Rating: 4.5
--------------------
  Name: Pink Metal
  Address: 253 Bushwick Ave, Brooklyn, NY 11206, USA
  Location: Latitude 40.7072591, Longitude -73.93954939999999
  Rating: 4.5
--------------------
  Name: Curry In Handi
  Address: 443 Bushwick Ave, Brooklyn, NY 11206, USA
  Location: Latitude 40.7023138, Longitude -73.9369236
  Rating: 4.8
--------------------
  Name: Eris
  Address: 167 Graham Ave, Brooklyn, NY 11206, USA
  Location: Latitude 40.7077096, Longitude -73.9436284
  Rating: 4.5
--------------------
  Name: Ange Noir Cafe
  Address: 247 Varet St, Brooklyn, NY 11206, USA
  Location: Latitude 40.7042159, Longitude -73.9341677
  Rating: 4.5
--------------------
Nearby Search Results:
  Name: Flaming Grill & Buffet
  Address: 2163 Tilden Ave, Brooklyn, NY 11226, USA
  Location: Latitude 40.6467004, Longitude -73.95742419999999
  Rating: 4.4
--------------------
  Name: McDonald's
  Address: 943 Flatbush Ave, Brooklyn, NY 11226, USA
  Location: Latitude 40.6487475, Longitude -73.95802549999999
  Rating: 3.7
--------------------
  Name: La Cabaña Rodríguez
  Address: 1062 Flatbush Ave, Brooklyn, NY 11226, USA
  Location: Latitude 40.6447824, Longitude -73.9582813
  Rating: 4.1
--------------------
  Name: Los tres Chiflados
  Address: 1046 Flatbush Ave, Brooklyn, NY 11226, USA
  Location: Latitude 40.6455141, Longitude -73.95835749999999
  Rating: 4.4
--------------------
  Name: Chipotle Mexican Grill
  Address: 1004 Flatbush Ave, Brooklyn, NY 11226, USA
  Location: Latitude 40.6467996, Longitude -73.95827249999999
  Rating: 2.1
--------------------
  Name: Wonder Flatbush
  Address: 2101 Church Ave, Brooklyn, NY 11226, USA
  Location: Latitude 40.6504924, Longitude -73.9595858
  Rating: 4.2
--------------------
  Name: Guac Time Mexican Grill
  Address: 1060 Flatbush Ave, Brooklyn, NY 11226, USA
  Location: Latitude 40.6449131, Longitude -73.9582771
  Rating: 4.5
--------------------
  Name: Wingstop
  Address: 946 Flatbush Ave, Brooklyn, NY 11226, USA
  Location: Latitude 40.648423, Longitude -73.9584768
  Rating: 3.3
--------------------
  Name: Starbucks
  Address: 2101 Church Ave, Brooklyn, NY 11226, USA
  Location: Latitude 40.6504055, Longitude -73.959709
  Rating: 4
--------------------
  Name: Taco Bell Cantina
  Address: 1034 Flatbush Ave, Brooklyn, NY 11226, USA
  Location: Latitude 40.6458011, Longitude -73.9583414
  Rating: 3.5
--------------------
  Name: Island Express
  Address: 998 Flatbush Ave, Brooklyn, NY 11226, USA
  Location: Latitude 40.647014, Longitude -73.958326
  Rating: 4.4
--------------------
  Name: FIB Tattoo Bar and Grill
  Address: 1051 Flatbush Ave, Brooklyn, NY 11226, USA
  Location: Latitude 40.645235, Longitude -73.957827
  Rating: 4.3
--------------------
  Name: Checkers
  Address: 1801 Church Ave, Brooklyn, NY 11226, USA
  Location: Latitude 40.6496633, Longitude -73.9629092
  Rating: 3.7
--------------------
  Name: Dunkin'
  Address: 1700 Church Ave, Brooklyn, NY 11226, USA
  Location: Latitude 40.6489609, Longitude -73.963808
  Rating: 3.6
--------------------
  Name: Popeyes Louisiana Kitchen
  Address: 970 Flatbush Ave, Brooklyn, NY 11226, USA
  Location: Latitude 40.647709899999995, Longitude -73.9583921
  Rating: 3.7
--------------------
  Name: Tex’s Chicken & Burgers
  Address: 521 Ocean Ave, Brooklyn, NY 11226, USA
  Location: Latitude 40.6499397, Longitude -73.96078510000001
  Rating: 4.2
--------------------
  Name: El Centenario Pizza
  Address: 57 E 18th St, Brooklyn, NY 11226, USA
  Location: Latitude 40.6499788, Longitude -73.9630459
  Rating: 4.9
--------------------
  Name: Golden Krust Caribbean Restaurant
  Address: 1617 Church Ave, Brooklyn, NY 11226, USA
  Location: Latitude 40.6491186, Longitude -73.96435720000001
  Rating: 3.6
--------------------
  Name: Steiny B's Smashburgers
  Address: 942 Flatbush Ave, Brooklyn, NY 11226, USA
  Location: Latitude 40.6485031, Longitude -73.95858969999999
  Rating: 4.7
--------------------
  Name: Subway
  Address: 2011 Church Ave, Brooklyn, NY 11226, USA
  Location: Latitude 40.6503124, Longitude -73.9605074
  Rating: 3.8
--------------------

In [33]:
requested_places

,formattedAddress,location,rating,displayName,latitude,longitude,address
0,"184 DeKalb Ave, Brooklyn, NY 11205, USA","{'latitude': 40.689425, 'longitude': -73.9723664}",4.6,"{'text': 'Miss Ada', 'languageCode': 'en'}",40.689887,-73.968178,284 Clinton Avenue
1,"171 Lafayette Ave, Brooklyn, NY 11238, USA","{'latitude': 40.6878197, 'longitude': -73.9706...",4.6,"{'text': 'Olea', 'languageCode': 'en'}",40.689887,-73.968178,284 Clinton Avenue
2,"387 Myrtle Ave, Brooklyn, NY 11205, USA","{'latitude': 40.6933422, 'longitude': -73.9704...",4.7,"{'text': 'LaRina Pastificio & Vino', 'language...",40.689887,-73.968178,284 Clinton Avenue
3,"166 DeKalb Ave, Brooklyn, NY 11217, USA","{'latitude': 40.6895015, 'longitude': -73.9732...",4.4,"{'text': 'Walter's', 'languageCode': 'en'}",40.689887,-73.968178,284 Clinton Avenue
4,"228 DeKalb Ave, Brooklyn, NY 11205, USA","{'latitude': 40.6893831, 'longitude': -73.9703...",4.4,"{'text': 'Sailor', 'languageCode': 'en'}",40.689887,-73.968178,284 Clinton Avenue
5,"197 Adelphi St, Brooklyn, NY 11205, USA","{'latitude': 40.6917328, 'longitude': -73.9714...",4.3,"{'text': 'Rhodora Wine Bar', 'languageCode': '...",40.689887,-73.968178,284 Clinton Avenue
6,"211 DeKalb Ave, Brooklyn, NY 11205, USA","{'latitude': 40.6897385, 'longitude': -73.970998}",4.7,"{'text': 'Evelina', 'languageCode': 'en'}",40.689887,-73.968178,284 Clinton Avenue
7,"219 DeKalb Ave, Brooklyn, NY 11205, USA","{'latitude': 40.689699399999995, 'longitude': ...",4.6,"{'text': 'Colonia Verde', 'languageCode': 'en'}",40.689887,-73.968178,284 Clinton Avenue
8,"247 DeKalb Ave, Brooklyn, NY 11205, USA","{'latitude': 40.689590599999995, 'longitude': ...",4.5,"{'text': 'Brooklyn Public House', 'languageCod...",40.689887,-73.968178,284 Clinton Avenue
9,"271 Adelphi St, Brooklyn, NY 11205, USA","{'latitude': 40.6894104, 'longitude': -73.9708...",4.4,"{'text': 'Mango Bay', 'languageCode': 'en'}",40.689887,-73.968178,284 Clinton Avenue
10,"120 Lafayette Ave, Brooklyn, NY 11238, USA","{'latitude': 40.687308699999996, 'longitude': ...",4.7,"{'text': 'Black Iris', 'languageCode': 'en'}",40.689887,-73.968178,284 Clinton Avenue
11,"143 Greene Ave, Brooklyn, NY 11238, USA","{'latitude': 40.6868, 'longitude': -73.9663178}",4.6,"{'text': 'Chef Katsu Brooklyn', 'languageCode'...",40.689887,-73.968178,284 Clinton Avenue
12,"243 DeKalb Ave, Brooklyn, NY 11205, USA","{'latitude': 40.689633, 'longitude': -73.96953...",4.6,"{'text': 'Roman's', 'languageCode': 'en'}",40.689887,-73.968178,284 Clinton Avenue
13,"357 Myrtle Ave, Brooklyn, NY 11205, USA","{'latitude': 40.693401099999996, 'longitude': ...",4.6,"{'text': 'Farmer in the Deli', 'languageCode':...",40.689887,-73.968178,284 Clinton Avenue
14,"147 Greene Ave, Brooklyn, NY 11238, USA","{'latitude': 40.6868526, 'longitude': -73.9662...",4.4,"{'text': 'Prima Brooklyn', 'languageCode': 'en'}",40.689887,-73.968178,284 Clinton Avenue
15,"438 Myrtle Ave, Brooklyn, NY 11205, USA","{'latitude': 40.692969, 'longitude': -73.96807...",4.8,"{'text': 'Myrtle Thai', 'languageCode': 'en'}",40.689887,-73.968178,284 Clinton Avenue
16,"132 Greene Ave, Brooklyn, NY 11238, USA","{'latitude': 40.6864911, 'longitude': -73.9666...",4.6,"{'text': 'Aita', 'languageCode': 'en'}",40.689887,-73.968178,284 Clinton Avenue
17,"177 Vanderbilt Ave, Brooklyn, NY 11205, USA","{'latitude': 40.692643, 'longitude': -73.9694925}",4.2,"{'text': 'Brooklyn Music Kitchen', 'languageCo...",40.689887,-73.968178,284 Clinton Avenue
18,"266 Adelphi St, Brooklyn, NY 11205, USA","{'latitude': 40.689854, 'longitude': -73.971357}",4.4,"{'text': 'Dick and Jane’s', 'languageCode': 'en'}",40.689887,-73.968178,284 Clinton Avenue
19,"274 Hall St, Brooklyn, NY 11205, USA","{'latitude': 40.6900427, 'longitude': -73.9654...",4.4,"{'text': 'Dinner Party', 'languageCode': 'en'}",40.689887,-73.968178,284 Clinton Avenue
0,"164 Graham Ave, Brooklyn, NY 11206, USA","{'latitude': 40.707242699999995, 'longitude': ...",4.5,"{'text': 'Win Son Bakery', 'languageCode': 'en'}",40.704791,-73.939378,172 Seigel Street
1,"260 Meserole St, Brooklyn, NY 11206, USA","{'latitude': 40.7084419, 'longitude': -73.9382...",4.3,"{'text': '3 Dollar Bill', 'languageCode': 'en'}",40.704791,-73.939378,172 Seigel Street
2,"261 Moore St, Brooklyn, NY 11206, USA","{'latitude': 40.705081, 'longitude': -73.9335834}",4.5,"{'text': 'Roberta's', 'languageCode': 'en'}",40.704791,-73.939378,172 Seigel Street
3,"159 Graham Ave, Brooklyn, NY 11206, USA","{'latitude': 40.7074661, 'longitude': -73.9434...",4.5,"{'text': 'Win Son', 'languageCode': 'en'}",40.704791,-73.939378,172 Seigel Street
4,"251 Bushwick Ave, Brooklyn, NY 11206, USA","{'latitude': 40.7073293, 'longitude': -73.9395...",4.7,"{'text': 'Sleepwalk', 'languageCode': 'en'}",40.704791,-73.939378,172 Seigel Street
5,"222 Varet St, Brooklyn, NY 11206, USA","{'latitude': 40.7037875, 'longitude': -73.9344...",4.9,"{'text': 'CLEO'S', 'languageCode': 'en'}",40.704791,-73.939378,172 Seigel Street
6,"222 Montrose Ave, Brooklyn, NY 11206, USA","{'latitude': 40.7074134, 'longitude': -73.9402...",4.6,"{'text': 'Dun-Well Doughnuts', 'languageCode':...",40.704791,-73.939378,172 Seigel Street
7,"153 Montrose Ave, Brooklyn, NY 11206, USA","{'latitude': 40.7074778, 'longitude': -73.9429...",4.4,"{'text': 'duckduck', 'languageCode': 'en'}",40.704791,-73.939378,172 Seigel Street
8,"169 Graham Ave, Brooklyn, NY 11206, USA","{'latitude': 40.7078148, 'longitude': -73.9435...",4.3,{'text': 'Lulla's Bakery - Grand Café & Cockta...,40.704791,-73.939378,172 Seigel Street
9,"32 Varet St, Brooklyn, NY 11206, USA","{'latitude': 40.702832099999995, 'longitude': ...",4.7,"{'text': 'Taqueria El Torito', 'languageCode':...",40.704791,-73.939378,172 Seigel Street
10,"135 Graham Ave, Brooklyn, NY 11206, USA","{'latitude': 40.7064375, 'longitude': -73.943238}",4.2,"{'text': 'Sweet Science', 'languageCode': 'en'}",40.704791,-73.939378,172 Seigel Street
11,"785 Flushing Ave, Brooklyn, NY 11206, USA","{'latitude': 40.7010024, 'longitude': -73.9412...",3.8,"{'text': 'IHOP', 'languageCode': 'en'}",40.704791,-73.939378,172 Seigel Street
12,"222 Bushwick Ave, Brooklyn, NY 11206, USA","{'latitude': 40.708203999999995, 'longitude': ...",4.6,"{'text': 'Tradesman', 'languageCode': 'en'}",40.704791,-73.939378,172 Seigel Street
13,"880 Flushing Ave, Brooklyn, NY 11206, USA","{'latitude': 40.7018895, 'longitude': -73.936578}",3.9,"{'text': 'MAMATACO', 'languageCode': 'en'}",40.704791,-73.939378,172 Seigel Street
14,"188 Montrose Ave, Brooklyn, NY 11206, USA","{'latitude': 40.7073209, 'longitude': -73.9418...",4.5,"{'text': 'The Brooklyn Tree', 'languageCode': ...",40.704791,-73.939378,172 Seigel Street
15,"108 Graham Ave, Brooklyn, NY 11206, USA","{'latitude': 40.7049447, 'longitude': -73.9426...",4.5,"{'text': 'Caridad China', 'languageCode': 'en'}",40.704791,-73.939378,172 Seigel Street
16,"253 Bushwick Ave, Brooklyn, NY 11206, USA","{'latitude': 40.7072591, 'longitude': -73.9395...",4.5,"{'text': 'Pink Metal', 'languageCode': 'en'}",40.704791,-73.939378,172 Seigel Street
17,"443 Bushwick Ave, Brooklyn, NY 11206, USA","{'latitude': 40.7023138, 'longitude': -73.9369...",4.8,"{'text': 'Curry In Handi', 'languageCode': 'en'}",40.704791,-73.939378,172 Seigel Street
18,"167 Graham Ave, Brooklyn, NY 11206, USA","{'latitude': 40.7077096, 'longitude': -73.9436...",4.5,"{'text': 'Eris', 'languageCode': 'en'}",40.704791,-73.939378,172 Seigel Street
19,"247 Varet St, Brooklyn, NY 11206, USA","{'latitude': 40.7042159, 'longitude': -73.9341...",4.5,"{'text': 'Ange Noir Cafe', 'languageCode': 'en'}",40.704791,-73.939378,172 Seigel Street
0,"2163 Tilden Ave, Brooklyn, NY 11226, USA","{'latitude': 40.6467004, 'longitude': -73.9574...",4.4,"{'text': 'Flaming Grill & Buffet', 'languageCo...",40.646504,-73.961568,116 East 19 Street
1,"943 Flatbush Ave, Brooklyn, NY 11226, USA","{'latitude': 40.6487475, 'longitude': -73.9580...",3.7,"{'text': 'McDonald's', 'languageCode': 'en'}",40.646504,-73.961568,116 East 19 Street
2,"1062 Flatbush Ave, Brooklyn, NY 11226, USA","{'latitude': 40.6447824, 'longitude': -73.9582...",4.1,"{'text': 'La Cabaña Rodríguez', 'languageCode'...",40.646504,-73.961568,116 East 19 Street
3,"1046 Flatbush Ave, Brooklyn, NY 11226, USA","{'latitude': 40.6455141, 'longitude': -73.9583...",4.4,"{'text': 'Los tres Chiflados', 'languageCode':...",40.646504,-73.961568,116 East 19 Street
4,"1004 Flatbush Ave, Brooklyn, NY 11226, USA","{'latitude': 40.6467996, 'longitude': -73.9582...",2.1,"{'text': 'Chipotle Mexican Grill', 'languageCo...",40.646504,-73.961568,116 East 19 Street
5,"2101 Church Ave, Brooklyn, NY 11226, USA","{'latitude': 40.6504924, 'longitude': -73.9595...",4.2,"{'text': 'Wonder Flatbush', 'languageCode': 'en'}",40.646504,-73.961568,116 East 19 Street
6,"1060 Flatbush Ave, Brooklyn, NY 11226, USA","{'latitude': 40.6449131, 'longitude': -73.9582...",4.5,"{'text': 'Guac Time Mexican Grill', 'languageC...",40.646504,-73.961568,116 East 19 Street
7,"946 Flatbush Ave, Brooklyn, NY 11226, USA","{'latitude': 40.648423, 'longitude': -73.9584768}",3.3,"{'text': 'Wingstop', 'languageCode': 'en'}",40.646504,-73.961568,116 East 19 Street
8,"2101 Church Ave, Brooklyn, NY 11226, USA","{'latitude': 40.6504055, 'longitude': -73.959709}",4.0,"{'text': 'Starbucks', 'languageCode': 'en'}",40.646504,-73.961568,116 East 19 Street
9,"1034 Flatbush Ave, Brooklyn, NY 11226, USA","{'latitude': 40.6458011, 'longitude': -73.9583...",3.5,"{'text': 'Taco Bell Cantina', 'languageCode': ...",40.646504,-73.961568,116 East 19 Street
10,"998 Flatbush Ave, Brooklyn, NY 11226, USA","{'latitude': 40.647014, 'longitude': -73.958326}",4.4,"{'text': 'Island Express', 'languageCode': 'en'}",40.646504,-73.961568,116 East 19 Street
11,"1051 Flatbush Ave, Brooklyn, NY 11226, USA","{'latitude': 40.645235, 'longitude': -73.957827}",4.3,"{'text': 'FIB Tattoo Bar and Grill', 'language...",40.646504,-73.961568,116 East 19 Street
12,"1801 Church Ave, Brooklyn, NY 11226, USA","{'latitude': 40.6496633, 'longitude': -73.9629...",3.7,"{'text': 'Checkers', 'languageCode': 'en'}",40.646504,-73.961568,116 East 19 Street
13,"1700 Church Ave, Brooklyn, NY 11226, USA","{'latitude': 40.6489609, 'longitude': -73.963808}",3.6,"{'text': 'Dunkin'', 'languageCode': 'en'}",40.646504,-73.961568,116 East 19 Street
14,"970 Flatbush Ave, Brooklyn, NY 11226, USA","{'latitude': 40.647709899999995, 'longitude': ...",3.7,"{'text': 'Popeyes Louisiana Kitchen', 'languag...",40.646504,-73.961568,116 East 19 Street
15,"521 Ocean Ave, Brooklyn, NY 11226, USA","{'latitude': 40.6499397, 'longitude': -73.9607...",4.2,"{'text': 'Tex’s Chicken & Burgers', 'languageC...",40.646504,-73.961568,116 East 19 Street
16,"57 E 18th St, Brooklyn, NY 11226, USA","{'latitude': 40.6499788, 'longitude': -73.9630...",4.9,"{'text': 'El Centenario Pizza', 'languageCode'...",40.646504,-73.961568,116 East 19 Street
17,"1617 Church Ave, Brooklyn, NY 11226, USA","{'latitude': 40.6491186, 'longitude': -73.9643...",3.6,"{'text': 'Golden Krust Caribbean Restaurant', ...",40.646504,-73.961568,116 East 19 Street
18,"942 Flatbush Ave, Brooklyn, NY 11226, USA","{'latitude': 40.6485031, 'longitude': -73.9585...",4.7,"{'text': 'Steiny B's Smashburgers', 'languageC...",40.646504,-73.961568,116 East 19 Street
19,"2011 Church Ave, Brooklyn, NY 11226, USA","{'latitude': 40.6503124, 'longitude': -73.9605...",3.8,"{'text': 'Subway', 'languageCode': 'en'}",40.646504,-73.961568,116 East 19 Street

In [27]:
requested_places.head(40)

,formattedAddress,location,rating,displayName,latitude,longitude,address
0,"28 Liberty St Suite SC301, New York, NY 10005,...","{'latitude': 40.7077585, 'longitude': -74.0088...",4.5,{'text': 'Alamo Drafthouse Cinema Lower Manhat...,40.689887,-73.968178,284 Clinton Avenue
1,"30 Water St, New York, NY 10004, USA","{'latitude': 40.7032685, 'longitude': -74.0110...",4.7,"{'text': 'The Dead Rabbit', 'languageCode': 'en'}",40.689887,-73.968178,284 Clinton Avenue
2,"54 Pearl St, New York, NY 10004, USA","{'latitude': 40.7034181, 'longitude': -74.0113...",4.5,"{'text': 'Fraunces Tavern', 'languageCode': 'en'}",40.689887,-73.968178,284 Clinton Avenue
3,"101 Liberty St, New York, NY 10007, USA","{'latitude': 40.710393599999996, 'longitude': ...",4.2,"{'text': 'Eataly', 'languageCode': 'en'}",40.689887,-73.968178,284 Clinton Avenue
4,"28 Liberty St 60th floor, New York, NY 10005, USA","{'latitude': 40.707997399999996, 'longitude': ...",4.7,"{'text': 'Manhatta', 'languageCode': 'en'}",40.689887,-73.968178,284 Clinton Avenue
5,"32 Broadway, New York, NY 10004, USA","{'latitude': 40.70587150000001, 'longitude': -...",4.5,"{'text': 'Liberty Bagels Wall Street', 'langua...",40.689887,-73.968178,284 Clinton Avenue
6,"6 Hanover St, New York, NY 10005, USA","{'latitude': 40.7054353, 'longitude': -74.0091...",4.4,"{'text': 'Conwell Coffee & Cocktail Hall', 'la...",40.689887,-73.968178,284 Clinton Avenue
7,"56 Beaver St, New York, NY 10004, USA","{'latitude': 40.705026800000006, 'longitude': ...",4.5,"{'text': 'Delmonico's', 'languageCode': 'en'}",40.689887,-73.968178,284 Clinton Avenue
8,"160 Broadway, New York, NY 10038, USA","{'latitude': 40.7094789, 'longitude': -74.0100...",3.8,"{'text': 'McDonald's', 'languageCode': 'en'}",40.689887,-73.968178,284 Clinton Avenue
9,"88 Wall St, New York, NY 10005, USA","{'latitude': 40.7055706, 'longitude': -74.007662}",4.8,"{'text': 'The Wall Street Hotel', 'languageCod...",40.689887,-73.968178,284 Clinton Avenue
10,"70 Pine St Ground Floor, New York, NY 10005, USA","{'latitude': 40.70619620000001, 'longitude': -...",4.5,"{'text': 'Crown Shy', 'languageCode': 'en'}",40.689887,-73.968178,284 Clinton Avenue
11,"70 Pine St 64th Floor, New York, NY 10005, USA","{'latitude': 40.706504699999996, 'longitude': ...",4.3,"{'text': 'Overstory', 'languageCode': 'en'}",40.689887,-73.968178,284 Clinton Avenue
12,"120 Cedar St, New York, NY 10006, USA","{'latitude': 40.7095008, 'longitude': -74.0126...",4.6,"{'text': 'O'Hara's Restaurant and Pub', 'langu...",40.689887,-73.968178,284 Clinton Avenue
13,"9 Maiden Ln, New York, NY 10038, USA","{'latitude': 40.70959, 'longitude': -74.009362}",4.6,"{'text': 'La Parisienne', 'languageCode': 'en'}",40.689887,-73.968178,284 Clinton Avenue
14,"41 John St, New York, NY 10038, USA","{'latitude': 40.709471, 'longitude': -74.00800...",4.8,"{'text': 'Apollo Bagels', 'languageCode': 'en'}",40.689887,-73.968178,284 Clinton Avenue
15,"1 Hanover Square, New York, NY 10004, USA","{'latitude': 40.704676299999996, 'longitude': ...",4.5,"{'text': 'Harry's', 'languageCode': 'en'}",40.689887,-73.968178,284 Clinton Avenue
16,"3 Hanover Square, New York, NY 10004, USA","{'latitude': 40.7049369, 'longitude': -74.0097...",4.3,"{'text': 'Leo's Bagels', 'languageCode': 'en'}",40.689887,-73.968178,284 Clinton Avenue
17,"123 Washington St, New York, NY 10006, USA","{'latitude': 40.7092191, 'longitude': -74.0137...",4.5,"{'text': 'Skinos', 'languageCode': 'en'}",40.689887,-73.968178,284 Clinton Avenue
18,"9 Maiden Ln, New York, NY 10038, USA","{'latitude': 40.7096649, 'longitude': -74.0093...",4.3,"{'text': 'The Malt House', 'languageCode': 'en'}",40.689887,-73.968178,284 Clinton Avenue
19,"83 Maiden Ln, New York, NY 10038, USA","{'latitude': 40.707454600000005, 'longitude': ...",4.7,"{'text': 'Mezcali', 'languageCode': 'en'}",40.689887,-73.968178,284 Clinton Avenue
0,"28 Liberty St Suite SC301, New York, NY 10005,...","{'latitude': 40.7077585, 'longitude': -74.0088...",4.5,{'text': 'Alamo Drafthouse Cinema Lower Manhat...,40.704791,-73.939378,172 Seigel Street
1,"30 Water St, New York, NY 10004, USA","{'latitude': 40.7032685, 'longitude': -74.0110...",4.7,"{'text': 'The Dead Rabbit', 'languageCode': 'en'}",40.704791,-73.939378,172 Seigel Street
2,"54 Pearl St, New York, NY 10004, USA","{'latitude': 40.7034181, 'longitude': -74.0113...",4.5,"{'text': 'Fraunces Tavern', 'languageCode': 'en'}",40.704791,-73.939378,172 Seigel Street
3,"101 Liberty St, New York, NY 10007, USA","{'latitude': 40.710393599999996, 'longitude': ...",4.2,"{'text': 'Eataly', 'languageCode': 'en'}",40.704791,-73.939378,172 Seigel Street
4,"28 Liberty St 60th floor, New York, NY 10005, USA","{'latitude': 40.707997399999996, 'longitude': ...",4.7,"{'text': 'Manhatta', 'languageCode': 'en'}",40.704791,-73.939378,172 Seigel Street
5,"32 Broadway, New York, NY 10004, USA","{'latitude': 40.70587150000001, 'longitude': -...",4.5,"{'text': 'Liberty Bagels Wall Street', 'langua...",40.704791,-73.939378,172 Seigel Street
6,"6 Hanover St, New York, NY 10005, USA","{'latitude': 40.7054353, 'longitude': -74.0091...",4.4,"{'text': 'Conwell Coffee & Cocktail Hall', 'la...",40.704791,-73.939378,172 Seigel Street
7,"56 Beaver St, New York, NY 10004, USA","{'latitude': 40.705026800000006, 'longitude': ...",4.5,"{'text': 'Delmonico's', 'languageCode': 'en'}",40.704791,-73.939378,172 Seigel Street
8,"160 Broadway, New York, NY 10038, USA","{'latitude': 40.7094789, 'longitude': -74.0100...",3.8,"{'text': 'McDonald's', 'languageCode': 'en'}",40.704791,-73.939378,172 Seigel Street
9,"88 Wall St, New York, NY 10005, USA","{'latitude': 40.7055706, 'longitude': -74.007662}",4.8,"{'text': 'The Wall Street Hotel', 'languageCod...",40.704791,-73.939378,172 Seigel Street
10,"70 Pine St Ground Floor, New York, NY 10005, USA","{'latitude': 40.70619620000001, 'longitude': -...",4.5,"{'text': 'Crown Shy', 'languageCode': 'en'}",40.704791,-73.939378,172 Seigel Street
11,"70 Pine St 64th Floor, New York, NY 10005, USA","{'latitude': 40.706504699999996, 'longitude': ...",4.3,"{'text': 'Overstory', 'languageCode': 'en'}",40.704791,-73.939378,172 Seigel Street
12,"120 Cedar St, New York, NY 10006, USA","{'latitude': 40.7095008, 'longitude': -74.0126...",4.6,"{'text': 'O'Hara's Restaurant and Pub', 'langu...",40.704791,-73.939378,172 Seigel Street
13,"9 Maiden Ln, New York, NY 10038, USA","{'latitude': 40.70959, 'longitude': -74.009362}",4.6,"{'text': 'La Parisienne', 'languageCode': 'en'}",40.704791,-73.939378,172 Seigel Street
14,"41 John St, New York, NY 10038, USA","{'latitude': 40.709471, 'longitude': -74.00800...",4.8,"{'text': 'Apollo Bagels', 'languageCode': 'en'}",40.704791,-73.939378,172 Seigel Street
15,"1 Hanover Square, New York, NY 10004, USA","{'latitude': 40.704676299999996, 'longitude': ...",4.5,"{'text': 'Harry's', 'languageCode': 'en'}",40.704791,-73.939378,172 Seigel Street
16,"3 Hanover Square, New York, NY 10004, USA","{'latitude': 40.7049369, 'longitude': -74.0097...",4.3,"{'text': 'Leo's Bagels', 'languageCode': 'en'}",40.704791,-73.939378,172 Seigel Street
17,"123 Washington St, New York, NY 10006, USA","{'latitude': 40.7092191, 'longitude': -74.0137...",4.5,"{'text': 'Skinos', 'languageCode': 'en'}",40.704791,-73.939378,172 Seigel Street
18,"9 Maiden Ln, New York, NY 10038, USA","{'latitude': 40.7096649, 'longitude': -74.0093...",4.3,"{'text': 'The Malt House', 'languageCode': 'en'}",40.704791,-73.939378,172 Seigel Street
19,"83 Maiden Ln, New York, NY 10038, USA","{'latitude': 40.707454600000005, 'longitude': ...",4.7,"{'text': 'Mezcali', 'languageCode': 'en'}",40.704791,-73.939378,172 Seigel Street